WikipediaLibrary/externallinks

extlinks/common/forms.py, extlinks/common/helpers.py, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/organisations/templates/organisations/organisation_detail.html, extlinks/organisations/templates/organisations/organisation_list.html, extlinks/organisations/views.py, extlinks/programs/templates/programs/program_charts_include.html, extlinks/programs/templates/programs/program_detail.html, extlinks/programs/templates/programs/program_list.html, extlinks/templates/base.html, extlinks/templates/documentation.html, extlinks/templates/homepage.html, extlinks/urls.py, extlinks/views.py, static/css/local.css
Somewhat closer to resembling the final UI. Still some UX concerns, but it looks more coherent now.
=> Overhaul of tool UI

extlinks/common/helpers.py, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/organisations/templates/organisations/organisation_list.html, extlinks/organisations/views.py
There's scope to do a whole bunch more here, specifically around constructing the graphs.
=> Db optimisation

.travis.yml, docker-compose.yml, extlinks/common/helpers.py, extlinks/common/views.py, extlinks/links/models.py, extlinks/organisations/models.py, extlinks/organisations/views.py, extlinks/programs/models.py, extlinks/programs/views.py, extlinks/settings/base.py, requirements/django.txt
Also includes some code optimisations
=> Add caching via memcached

extlinks/programs/templates/programs/program_detail.html
Task that (I believe) I've accomplished for GCI2019.
=> Retain filterring when navigating from a Program to an Organisation in Wikilink tool

extlinks/common/helpers.py, extlinks/links/management/commands/linkevent_example_data.py, extlinks/programs/management/commands/programs_example_data.py
Example data scripts should work now.
Another optimisation commit snuck through here too, forgot I hadn't pushed that yet.
=> Example data fixes

.gitignore, extlinks/common/forms.py, extlinks/common/helpers.py, extlinks/organisations/templates/organisations/organisation_detail.html, extlinks/organisations/tests.py, extlinks/programs/templates/programs/program_detail.html, extlinks/programs/tests.py
https://phabricator.wikimedia.org/T228987, https://codein.withgoogle.com/dashboard/task-instances/6133879677648896/
Still need to add tests, however I have no idea where.
=> Add support for filtering for namespace

Dockerfile, bin/django_wait_for_db.sh, extlinks/settings/base.py, extlinks/settings/local.py, extlinks/settings/logging.py, extlinks/settings/production.py, extlinks/settings/staging.py, extlinks/templates/base.html, manage.py, requirements/django.txt
Upgrading to Django 3.1.
After conducting an investigation in task [T250084](https://phabricator.wikimedia.org/T250084) to check why the EventStream kept disconnecting, the team concluded that the data collection script needs to be refactored. This refactoring will take place on another ticket, but first, we need to upgrade the Django version to exploit the new features like a JSON field that might be needed in the algorithm refactoring and Async views for making expensive queries without having the server crash out.
[T261798](https://phabricator.wikimedia.org/T261798)
[//]: # (- Can …
=> Upgrade to Django 3.1

extlinks/settings/local.py, requirements/local.txt
Added the `django-extensions` library.
This library adds a lot of useful management commands like `shell_plus`. This will only be added to the local development environment when run with the `REQUIREMENTS_FILE` build environment variable.
N/A
=> Add Django extensions

extlinks/links/migrations/0008_fill_proquest_openurl.py
Migration was not running as expected in production
=> Fix ProQuest OpenURL migration

extlinks/settings/logging.py, extlinks/settings/production.py, extlinks/settings/staging.py, extlinks/urls.py, requirements/django.txt
Implemented GlitchTip for Wikilink.
Since we just implemented GlitchTip in the Wikipedia Library, we thought it would be good to also have an exception logging service in Wikilink. This will give us more visibility on errors that are occurring in the app.
[T262931](https://phabricator.wikimedia.org/T262931)
Pushed the changes to staging and forced an error.
=> Set up GlitchTip for Wikilink

extlinks/organisations/admin.py, extlinks/organisations/models.py, extlinks/organisations/views.py
Some minor improvements for the application and the admin:
- Added filters in organization and collection admin views
- Removed an unused `@property` in Organization
- Ordered the organizations' list view by name
Helps improve our workflow
[T297193](https://phabricator.wikimedia.org/T297193)
=> Admin improvements

extlinks/common/templates/common/statistics_table.html, extlinks/common/templates/common/top_organisations_table.html, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/programs/templates/programs/program_charts_include.html, extlinks/programs/tests.py, extlinks/programs/urls.py, extlinks/programs/views.py, extlinks/templates/base.html
Changed most queries in the program detail view to Ajax requests.
This has sped up the site's first paint since the heavier queries are now loaded asynchronously via Ajax
N/A
=> Change most queries to Ajax requests

extlinks/links/management/commands/linkevents_collect.py, extlinks/organisations/models.py, extlinks/programs/models.py
Capturing small improvements made while trying to find more performance for linkevents_collect
=> qs.exists() can be faster than if qs.count() > 0

docker-compose.yml, extlinks/aggregates/apps.py, extlinks/aggregates/cron.py, extlinks/common/cron.py, extlinks/healthcheck/apps.py, extlinks/links/apps.py, extlinks/links/cron.py, extlinks/links/management/commands/linkevents_collect.py, extlinks/organisations/cron.py, extlinks/programs/apps.py, extlinks/programs/urls.py, extlinks/settings/base.py, requirements/django.txt
Upgrading to the latest LTS version, Django 4.2.
Keeping Wikilink up to date is important, and the LTS version will guarantee security updates for a few years before we need to do another big upgrade. 
[T349552](https://phabricator.wikimedia.org/T349552)
Tested manually and with automated tests.
=> Upgrade to Django 4.2

docker-compose.yml, extlinks/settings/base.py
Doubled the cache memory in docker-compose file and added cache settings to manage network errors as cache misses.
This will help fix intermittent errors in organisations.user_list cron and aggregates.user_aggregates cron
[T350298](https://phabricator.wikimedia.org/T350298)
=> Increase cache memory and modify cache settings

extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/aggregates/tests.py
- Skip collections where organisations don't exist for all aggregate commands.
- Added tests
Fixes bugs that have broken the management commands
[T366978](https://phabricator.wikimedia.org/T366978)
=> Fix aggregate commands bugs

extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/aggregates/tests.py, extlinks/common/tests.py, extlinks/links/factories.py, extlinks/links/tests.py, extlinks/organisations/tests.py, extlinks/programs/tests.py
This is just a small optimization followup for #345.
I streamlined a few more db queries (that hopefully produce identical results) and got rid of a bunch of test warnings
https://phabricator.wikimedia.org/T366978
I ran the django test suite. I didn't do any manual testing. This could use a look!
=> Jsn.sherman/t366978 followup

.github/workflows/dockerpublish.yml
[//]: # (Thank you for uploading a PR to Wikilinks (externallinks)!)
Updates github actions to versions that use node 20
Node 16 is deprecated and actions that use it are throwing warnings
N/A
This PR is the test
N/A
=> github actions: use node 20

db.cnf
Increase a couple of timeout values in MySQL configuration.
We are still experiencing some MySQL has gone away and lost connection to MySQL during query errors. Increasing these values may help.
[T366978](https://phabricator.wikimedia.org/T366978)
=> Increase timeout values

extlinks/aggregates/management/commands/fill_pageproject_aggregates.py
Add logic to isolate problem aggregate records and log them out for further investigation.
Bug: T366978
By using the get_or_create function when saving a new PageProjectAggregate record we can isolate and identify the records that are causing issues in production. 
Adding additional error handling to the create function to stop the job from crashing as well as add logging for problematic records. 
https://phabricator.wikimedia.org/T366978
[//]: # (- …
=> [Wikilink] Aggregates maintenance commands errors

nginx.conf
Bug: T368660
Disallow bots from scraping wikilink.
https://phabricator.wikimedia.org/T368660
Cannot test locally due to it being nginx config.
=> Disallow bots on Wikilink

requirements/local.txt
Added [pudb](https://documen.tician.de/pudb/) for better debugging in Wikilink
This will help debug some of the hairier bugs on Wikilink by stepping into Django code, amongst other things.
N/A
=> Add pudb for local debugging

docker-compose.yml
Change-Id: I19f4434b41c066e05671ef3938addf90abcc92ab
[//]: # (Thank you for uploading a PR to Wikilinks (externallinks)!)
=> Hotfix for docker image name push

extlinks/aggregates/management/helpers/aggregate_archive_command.py
Add try/except to ensure_container_exists in aggregate archive
This is failing in production, and the clause will help us figure out why.
=> Add try/except to ensure_container_exists in aggregate archive

extlinks/aggregates/management/helpers/aggregate_archive_command.py
- Fix logging output
Bug: T396681
Change-Id: I545f94907b356629a22b682d2c0778068c619c01
Reformat logs for debugging so that they actually print out to the console. 
Debugging container not found issue, and noticed none of our error logging is happening. 
https://phabricator.wikimedia.org/T396681
Ran tests locally, ran the commands locally. 
=> Create cron tasks for archiving aggregates

extlinks/organisations/views.py
Adds type checks and early returns for collection id parameter input on organization views
We're currently throwing 500s for valid requests where we could simply return empty results.
https://phabricator.wikimedia.org/T401431
Manual local testing
=> orgs: handle invalid/missing collection ids
