WikipediaLibrary/externallinks

extlinks/common/helpers.py, extlinks/common/tests.py, extlinks/common/views.py, extlinks/links/factories.py, extlinks/organisations/factories.py
We were overcounting in the case that a LinkEvent was part of multiple URLs. Added a test and fix for this.
=> Fix totals duplicating counts

extlinks/common/helpers.py
Two queries per day shown to two queries total. Still a little messy because we need to line up the dates for additions and removals but this should be much better in terms of performance.
=> Severely reduce number of database calls required to build graph

extlinks/common/templatetags/common_filters.py, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/programs/templates/programs/program_charts_include.html
We could have done this with a model method but it wouldn't have worked so well with the top page annotations. Easier to make a catch-all custom filter.
=> Remove underscores from page titles

extlinks/common/helpers.py, extlinks/programs/views.py
- Only `select_related` when we need it, rather than for every query.
- Use `.distinct().count()` on our original queryset instead of `len()` on a more complicated one.
=> Minor queryset optimisations

extlinks/common/forms.py, extlinks/common/helpers.py, extlinks/organisations/models.py, extlinks/organisations/templates/organisations/organisation_detail.html, extlinks/organisations/tests.py, extlinks/programs/models.py, extlinks/programs/templates/programs/program_detail.html, extlinks/programs/tests.py
Change is added to remove bot edits within programs and organisations. Reviewers can test code
through extlinks/programs/tests.py and extlinks/organisations/tests.py
Bug: T228384
=> extlinks: Add filter to remove bot edits

extlinks/links/management/commands/linkevents_collect.py
We simply skip the URL if its length is very large.
https://phabricator.wikimedia.org/T241991
=> Fix "Data too long for column 'link'" error

extlinks/templates/base.html
To comply with WIkimedia's privacy policy, using the tool mentioned at https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web#External_assets to load external assets.
=> replace direct url of external assets with proxy url

requirements/django.txt
Changed Django requirements to always install the latest version of
Django 2.2 instead of a fixed one.
=> Change Django requirements

extlinks/links/helpers.py, extlinks/links/management/commands/linkevents_collect.py, extlinks/links/models.py, extlinks/links/tests.py
This change does three things:
- Adds tracking of Wikipedia Library proxied versions of URLs so that if a user adds a citation to, for example, `https://www-test-com.wikipedialibrary.idm.oclc.org/`, we track it if we're tracking `test.com`
- Refactors the tracking script so that it's easier to work with and test
- Adds tests for the logic that decides whether we care about tracking a particular URL, which was notably missing.
We're currently missing a substantial amount of links being added by editors who add proxied versions of the URL in their citation. That's not inherently a problem because there's a bot that tidies those up afterwards on-wiki, but we want to know that we tracked them using our resources.
https://phabricator.wikimedia.org/T262025
I added a set of new tests covering …
=> Track proxied URLs + refactor/test link tracking

bin/backup.sh, bin/gunicorn.sh, bin/restore.sh
While testing the deployment against production data, I encountered several issues:
1) The current production system was experience higher system load than expected given the instantaneous traffic and scheduled tasks running. This was partially due to the gunicorn configuration being somewhat mismatched to the resources of the server
2) While attempting to restore production data to the staging environment, the script failed out due to lack of system memory. I had written the backup/restore scripts to use the `dumpdata`/`loaddata` management commands to provide logical json-based backups since this would ease any future changes to the db backend. …
=> T258793: resolve more blockers to Wikilink production swarm

bin/backup.sh
We should retain backups for 90 days. This automatically deletes old backups. The worlds tiniest PR.
The primary concern here is disk usage. Currently, the disk usage will increase indefinitely.
https://phabricator.wikimedia.org/T254327
- I created a backup `202009301535.sql.gz` and then set it's modification time to be older than 90 days by running `touch -m --date="2020-01-01 00:00" backup/202009301535.sql.gz`
- I then deleted the gzip binary from the running image.
- I ran another backup, which failed. The backup script has the `-e` option set, meaning that if the db dump fails, the old backups should not be deleted.
- The old backup was still there.
- I then halted and deleted that container and reran `docker-compose up` and ran another backup.
- A new backup was created successfully …
=> delete backups older than 90 days.

extlinks/links/management/commands/linkevents_collect.py
Adds timeout and retry delay values to SSE client in linkevent collection command.
Currently, the evenstream container hangs on a regular basis. This should allow the container to either time out and retry or fail out so that docker swarm can restart it.
https://phabricator.wikimedia.org/T264211
Ran `docker exec -it $(docker ps -aq -f name=staging_externallinks | head -n 1) python manage.py linkevents_collect --historical` on staging and it didn't blow up. I can't really test any further unless we discover why the eventstream container almost immediately exits in non-production environments.
N/A
=> Configure SSE Client retry and timeout behavior.

.gitignore, Dockerfile, README.md, extlinks/settings/local.py, extlinks/urls.py, requirements/local.txt
Added the Django Debug Toolbar library.
This library will help us with debugging issues, such as the one described in [T240673](https://phabricator.wikimedia.org/T240673)
[T240673](https://phabricator.wikimedia.org/T240673)
1. Run `docker-compose build && docker-compose up`. This shouldn't display the Django Debug Toolbar.
2. Run `docker-compose build --build-arg REQUIREMENTS_FILE=local.txt && docker-compose up`. This should display the Django Debug Toolbar.
**Docker …
=> Add Django Debug Toolbar to local dev environments

.github/workflows/dockerpublish.yml, Dockerfile, bin/swarm_update.sh, docker-compose.yml
Replace docker.io with quay.io for wikilink images.
The newly enforced docker hub pull rate limits make our deployment pipeline too unpredictable
https://www.docker.com/increase-rate-limits
https://phabricator.wikimedia.org/T270082
Our testing capabilities on this are limited since this is an in-band change to our deployment infrastructure.
N/A
=> WIP Replace docker.io with quay.io for wikilink images

extlinks/common/templates/common/statistics_table.html, extlinks/common/templates/common/top_organisations_table.html, extlinks/common/templates/common/top_pages_table.html, extlinks/common/templates/common/top_projects_table.html, extlinks/common/templates/common/top_users_table.html, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/organisations/views.py, extlinks/programs/templates/programs/program_charts_include.html, extlinks/programs/views.py, static/css/local.css
After merging #55, we noticed that the Totals tables bump into each other because of the extra column added. This happened on certain screen sizes.
This PR removes the `Links Added` and `Links Removed` columns from the `Totals` tables. Note that these columns will still appear when a  user wants to download a CSV file with the relevant information. 
[T270335](https://phabricator.wikimedia.org/T270335)
This was tested manually, on screens of different sizes. …
=> Show Net Change only in Total tables

extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/aggregates/tests.py, extlinks/organisations/views.py
A `DoesNotExist` error appears when a collection does not have information on the `LinkAggregate` table. Upon further inspection, the collection that has that error should have information. To fix this before this PR, we would have to clear the `LinkAggregate` table and run the `fill_link_aggregates` command again. Instead of doing that, we can now run the command so that it fills data for certain collections that weren't filled properly.
This will help fix any counting errors in certain collections without having to clear all of the information in an aggregate table.
[T270427](https://phabricator.wikimedia.org/T270427)
[//]: # (- Did you add tests to your changes? Did you modify …
=> Bug fix: DoesNotExistError

.gitignore, extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/links/migrations/0008_fill_proquest_openurl.py
The `Proquest Open URL` collection was showing no data in the organization detail view. This was due to the fact that no link events were added to the URLPattern that is related to that collection. 
By adding a migration to fix this, the aggregate management commands can be run so that that collection has information.
N/A
Manually tested the migration and ran the aggregates commands for that collection.
What types of changes does your code introduce? Add an `x` in …
=> Add migration to fix Proquest Open URL linkevents

extlinks/common/helpers.py, extlinks/common/views.py, extlinks/organisations/views.py
This PR fixes a bug where the Link Events list wasn't being filtered correctly in the organization detail view.
When 'Limit to user list' is selected, the table of the latest link events should also be updated to only show the latest events from users on the user list.
[T271414](https://phabricator.wikimedia.org/T271414)
1. Go to a random organization
2. Filter it by checking `Limit to user list`
3. See that the results are being filtered
**With no filter**
**With …
=> Fix user list filter in organisation linkevents

extlinks/organisations/views.py, extlinks/programs/views.py
Added an `order_by` clause in a LinkAggregate query.
Sometimes, the dates would present themselves out of order. By adding the `order_by` clause, we can force the query to consistently return data in the desired order.
[T271408](https://phabricator.wikimedia.org/T271408)
I have not been able to reproduce this error locally
=> Add order by clause in LinkAggregate chart query

docker-compose.yml, template.env
We previously established automated backups (T254327), but since we were waiting on a project NFS share, they were stored on the local filesystem. Now that we have that NFS share (T264107), we need to update the puppet config to enable access for the production instance and add an appropriate bind mount to our docker compose, just like we've done in TWLight.
This improves our backup durability and abillity to recover from oopsies.
https://phabricator.wikimedia.org/T271110
I tested the new default mount (same location as the old implicit one) locally. There's not much of a way to test this other than to get it deployed, but we're doing exactly the same thing in TWLight.
NA
=> Store wikilink backups on nfs share

extlinks/organisations/views.py, extlinks/programs/views.py
When there was no information for a month, the graph was not displaying that month (not even a zero). This PR fixes this bug.
Even if there is a 0 data point for a month, we should show that and not skip the month, for clarity.
[T271409](https://phabricator.wikimedia.org/T271409)
1. Go to a program or organization
2. Select the `Limit to user list` filter
3. Verify that every month is still displayed (even with a zero)
**Before**
Only two months are being displayed …
=> Add 0 if there is no data in month when filling charts

extlinks/common/helpers.py, extlinks/organisations/views.py, extlinks/programs/views.py
There was an `Exception Value: can't compare datetime.datetime to datetime.date` when trying to get information from organizations or programs. 
There was also a minor bug in the building of the Q object to filter by `end_date`. 
This solves bugs that impede functionality.
[T272363](https://phabricator.wikimedia.org/T272363)
Tested manually.
=> Fix date comparison error

extlinks/links/management/commands/linkevents_collect.py, extlinks/links/management/commands/remove_ezproxy_collection.py, extlinks/links/tests.py
* Created a management command that removes the EZProxy collection, organization and url patterns associated with them and then add that proxied url to the collection it actually belongs to
* Changed the `linkevents_collect` command to do the same going forward
When editors cite a resource from The Wikipedia Library, they might have accessed it through EZProxy. These citation events were being missed from our metrics. This PR solves this problem
[T262025](https://phabricator.wikimedia.org/T262025)
Manual testing of the management …
=> Track proxy urls

extlinks/links/management/commands/fix_proxy_linkevents_on_user_list.py, extlinks/links/management/commands/remove_ezproxy_collection.py, extlinks/links/tests.py
Created a management command to change the `on_user_list` flag of a proxy LinkEvent if a user is a part of that organization's user list.
Most of these links must have editors who were on the user list of that organization. Since we do not store historical data about when editors have or have not been on a user list, we will use the current status as the modified `on_user_list` flag.
[T273078](https://phabricator.wikimedia.org/T273078)
Manual testing the command and created a test.
[//]: # (It can also be a GIF to prove that your …
=> Fix on_user_list flag on proxy linkevents

extlinks/settings/helpers.py, extlinks/settings/production.py, extlinks/settings/staging.py
This is a quick fix (note the lack of unit tests) that I almost hotfixed in , but I thought could use a second set of eyes.
Since we're no longer using Django's builtin error logging, we no longer get the benefit of the builtin data scrubbing. So, we'll scrub it ourselves!
https://phabricator.wikimedia.org/T275521
I did the following manual test:
- pulled down some event json from glitchtip
- imported the new callback into my interactive python shell
- fed the event to the callback
- checked the output data, which was now masked at several levels
N/A
=> scrub glitchtip event data

extlinks/links/management/commands/linksearchtotal_collect.py
This simply updates the replica db hostnames to reflect the new replica cluster.
https://wikitech.wikimedia.org/wiki/News/Wiki_Replicas_2020_Redesign#New_host_names
N/A
N/A
N/A
=> Use new hostnames for Wiki Replicas

docker-compose.yml, extlinks/links/management/commands/linkevents_collect.py, nginx.conf
- Adds an nginx proxy cache for anonymous users, which allows us to serve content even if the externallinks service is unresponsive
- cleans up some small bugs in the nginx config
- prettifies docker-compose.yml
Also has a quick fix to a bug I discovered post-moving-things around:
```
eventstream_1    | Traceback (most recent call last):
eventstream_1    |   File "django_wait_for_migrations.py", line 59, in <module>
eventstream_1    |     wait_for_migrations(sys.argv)
eventstream_1    |   File "django_wait_for_migrations.py", line 53, in wait_for_migrations
eventstream_1    |     execute_from_command_line(args)
eventstream_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
eventstream_1    | …
```
=> Use nginx proxy cache to serve stale content as needed

extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py
Prefetch related URLs in single collection filtering in management commands
URLs were being prefetched when looping through all collections, but not when looping through a determined set of collections.
N/A
Manually tested the management commands
=> Add prefetch_related to single collection filtering in management commands

docker-compose.yml
Adds resource reservations, which only come into play during resource contention on the host.
Occasionally, once of the services will consume 100% of system resources, leaving nothing for the other services to operate. This is the minimum amount of change to try to address that. When there is no contention, services will continue to consume as much as they want.
The initial values here were determined by looking at `docker stats` in production
```
NAME                                                   CPU %     MEM USAGE / LIMIT     MEM % 
production_eventstream                                 5.45%     39.05MiB / 7.773GiB   0.49%
production_nginx                                       0.21%     14.75MiB / 7.773GiB   0.19%
production_externallinks                               0.63% …
```
=> Add resource quotas to Wikilink services

extlinks/aggregates/factories.py, extlinks/links/management/commands/linkevents_collect.py, extlinks/links/models.py
Caches the queryset of url patterns called when saving link events to the db.
Deletes the cache when a url pattern is saved.
This precludes a db tablescan from happening for every event saved.
N/A
I restored a backup and ran the linkevent collection container. I measured the time to parse events before and after and found 19% improvement for ingest speed. I also saw lower overall RAM utilization, but I am less confident in a causal relationship with that. I also tested updating and creating url patterns and verified that the cache gets deleted by the save, and recreated by the ingest command.
N/A
=> cache url patterns used in linkevents_collect

db.cnf, extlinks/links/management/commands/linkevents_archive.py, extlinks/links/management/commands/linkevents_collect.py, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/programs/templates/programs/program_charts_include.html
Adds management command for dumping linkevents from past years out to gzipped json fixture files.
Updates `csv_all_links` downloads to specify that they are for the current year only
We have over 5 million rows in the linkevents table, and most of that data has been aggregated. We do check for duplicate event ids coming through the stream, but we expect them to be happening near to each other in time, not years apart. Dumping these out will allow us a lot more performance headroom on the production system while still preserving the data if we need to recalculate our aggregates for some reason.
https://phabricator.wikimedia.org/T330416
I wrote a little script to
1. restore a backup
1. dump (and delete) the linkevents from prior years
1. load those same events
It counts the linkevents …
=> linkevents_archive: dump+delete/load eventlinks

extlinks/common/views.py, extlinks/programs/templates/programs/program_charts_include.html, extlinks/programs/tests.py
Removed the CSV  download all links button and view logic from programs. The behavior for individual organizations stayed as-is.
Attempting to download all link events was very costly and would break.
[T331459](https://phabricator.wikimedia.org/T331459)
Tested manually and automated tests are running correctly.
=> Remove CSV all links button and view logic from programs

extlinks/aggregates/cron.py, extlinks/common/cron.py, extlinks/links/cron.py, extlinks/organisations/cron.py
Added the retry_after_failure_mins in the schedule constructor.
The crons will retry more frequently after failures, which can cause a server overload.
[T350295](https://phabricator.wikimedia.org/T350295)
=> Fix django-cron jobs

extlinks/links/management/commands/linksearchtotal_collect.py
Changed the externallinks field we use in the WHERE clause from el_index to el_to_domain_index to fit the new table schema.
This management command is broken.
[T350298](https://phabricator.wikimedia.org/T350298)
=> Change externallinks field in WHERE clause

extlinks/healthcheck/urls.py, extlinks/healthcheck/views.py
adds the following endpoints:
- /healthcheck/agg_crons
- healthy if all [aggregate jobs](https://github.com/WikipediaLibrary/externallinks/blob/master/extlinks/aggregates/cron.py) have succeeded in the last 2 days
- /healthcheck/common_crons
- healthy if [backup job](https://github.com/WikipediaLibrary/externallinks/blob/master/extlinks/common/cron.py) has succeded in the last 2 days
- /healthcheck/link_crons
- healthy if [links cron](https://github.com/WikipediaLibrary/externallinks/blob/master/extlinks/links/cron.py) has succeded in the last 9 days
- /healthcheck/org_crons
- healthy if [user list job](https://github.com/WikipediaLibrary/externallinks/blob/master/extlinks/organisations/cron.py) has succeeded within the last 2 hours
This will allow us to get email notifications from an …
=> healthcheck: add endpoints for cron jobs

bin/backup.sh, extlinks/common/cron.py, extlinks/healthcheck/views.py
Reduce backup frequency and retention
Our backups use too much disk space:
- every other day still provides plenty of restore times within our one week of event stream data
- backups older than two weeks are of limited utility because of the amount of data loss due to the event data stream only going back ~7 days
https://phabricator.wikimedia.org/T350295
I tested this locally, and it seems to work fine.
=> backup: run every 2 days; retain for 2 weeks

bin/restore.sh
[//]: # (Thank you for uploading a PR to Wikilinks (externallinks)!)
the decompression and db writes can be very cpu and io intensive. Moving the commands into a subshell and setting a nice value on that shell allows other system processes to continue while restoring.
restoring locally rendered my dev toolchain inoperable; it has previously rendered the production system inaccessible via ssh.
N/A
This was how I did my most recent local restore
N/A
=> restore.sh: set nice value to prevent self-DOS

extlinks/organisations/templates/organisations/organisation_charts_include.html
Add string truncation in page stats table
The strings of long article names overflow into the next table
N/A
Tested manually
**Before**
**After**
=> Add string truncation in page stats table

bin/backup.sh
the compression and mysqldump can be very cpu and io intensive. Moving the commands into a subshell and setting a nice value on that shell allows other system processes to continue while backing up.
It looks like the externallinks container can't reliably access the database while backups are running. Reducing the priority of the gzip and mysqldump processes should help with that
N/A
I ran a backup locally while collecting events. The backup finished a little slower, which indicates that it had lower priority during periods of contention.
N/A
=> backup.sh: set nice value to prevent self-DOS

db.cnf, extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py
- Added atomic transactions when creating new aggregates rows in the management commands
- Increased `max_allowed_packet` in db.cnf
This will help not create duplicate rows in the aggregates tables, which was causing failures in the cron jobs
[T366978](https://phabricator.wikimedia.org/T366978)
=> Add atomic transactions to aggregates commands

bin/restore.sh
Added extra echos before dropping the database.
Sometimes, people can accidentally run that command and drop a database with tens of millions of rows.  We'd rather not do that.
N/A
=> Add extra echos to restore script

extlinks/organisations/templates/organisations/organisation_charts_include.html
Changed several variables from `const` and `let` to `var`.
The variables were declared const and let, which is good when there is only one collection, but there is a runtime error when there is more than 1 collection in the organisation view.
N/A
=> Fix `organisation_include_charts` variable declaration

nginx.conf
Bug: T368660
Add bots to nginx config to disallow them from scraping wikilink. 
We have noticed in GlitchTip that there has been an increase in errors when trying to download CSV files from collections. Upon further inspection, we realized that two bots were making requests to collections that did not exist. We should disallow them from the site.
DotBot: https://moz.com/help/moz-procedures/crawlers/dotbot#block-dotbot-from-any-part-of-your-site
FacebookBot: https://developers.facebook.com/docs/sharing/bot/ …
=> Disallow bots on Wikilink

extlinks/organisations/cron.py
Bug: T351654
Update the RUN_EVERY_MINS variable like in the [documentation](https://django-cron.readthedocs.io/en/latest/installation.html). 
user_lists_cron should be running hourly, not daily, in Wikilink
https://phabricator.wikimedia.org/T351654
Ran cron locally. 
What types of changes does your code introduce? Add an `x` in …
=> user_lists_cron should be running hourly, not daily, in Wikilink

nginx.conf
generic relationships on LinkEvents
Bug: T370901
- Increased proxy_connect_timeout, proxy_send_timeout, and proxy_read_timeout to 120 seconds for admin path. 
- Increased send_timeout and keepalive_timeout to 120 seconds for admin path.
So we can validate if the generic relationship migration is successful, and to allow the admin dashboard some extra time. 
https://phabricator.wikimedia.org/T370901
Not tested since we only have one environment 
=> Increase timeout in nginx config for admin paths so we can validate

extlinks/links/admin.py, extlinks/organisations/admin.py
- Added `autocomplete_fields` to URLPattern admin view 
We need to be able to look at link events and URL patterns in the admin views.
[T370901](https://phabricator.wikimedia.org/T370901)
=> Improve performance of URLPattern admin

extlinks/common/urls.py, extlinks/common/views.py, extlinks/links/cron.py, extlinks/links/management/commands/linkevents_archive.py, extlinks/links/tests.py, extlinks/organisations/templates/organisations/organisation_charts_include.html, extlinks/organisations/tests.py
This patch changes the linkevents_archive command to archive LinkEvents by day rather than by year. Previously this command would archive LinkEvents by year and split them into multiple chunks of 100k records.
* Removed the 'year' parameter and handling.
* Added an optional 'date' parameter to linkevents_archive that the command scans backwards from.
* Added an optional 'output' parameter to linkevents_archive to tell it where to put the archives. This defaults to 'backup' and this option is used by the tests.
* Added a cron job that archives LinkEvents daily at 02:00 UTC.
* When 'date' is left unspecified (e.g. from the cron job) then a safe date to begin archiving from is determined by checking when the aggregation jobs have most recently completed.
* Added tests for the archive …
=> linkevents_archive: Rework command to split archives by date

extlinks/aggregates/cron.py, extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_link_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_user_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/aggregates/tests.py
- the commands will now process the oldest available month of aggregates by default
- it will not process data that falls within the last 10 days
- updates monthly aggregate crons to run every 5 minutes
- changes command logging and cron calls to commands to provide log info in django cron log objects
This change will allow us to process our backlog of monthly aggregates without intervention and with better logging.
https://phabricator.wikimedia.org/T370977
I did manual local testing to verify; I updated existing tests to pass
Before logging change:
After logging change:
=> contiuously process oldest monthly aggregates

db.cnf
Variables that were increased:
- max_allowed_packet
- connect_timeout
Change-Id: I983b96b4260f10d08f95027254233a16447a6d30
Describe your changes in detail following the [commit message guidelines]
Increase time on mysql server variables due to mysql errors. 
Hopefully fixes (2006, 'MySQL server has gone away') issue we are seeing in production when running cron jobs. 
No ticket
=> Increase time and size of mysql server variables

extlinks/aggregates/management/commands/fill_link_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_link_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_user_aggregates.py, extlinks/aggregates/management/commands/fill_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_user_aggregates.py, extlinks/aggregates/tests.py, extlinks/links/management/commands/linkevents_archive.py, extlinks/links/management/commands/linksearchtotal_collect.py, extlinks/links/tests.py, extlinks/organisations/management/commands/users_update_lists.py, extlinks/organisations/tests.py, extlinks/programs/tests.py
Add the `close_old_connections` function to most crons.
We have observed several lingering stale DB connections whenever there are multiple errors in the crown jobs. This hopes to solve it.
N/A
Changed the tests and manual testing.
=> Add close_old_connections function to most crons

extlinks/settings/base.py
Decrease the time django-cron logs are kept to 90 days.
Before, we had more errors in our cron jobs, so we had to keep a larger historical record. Since we will be running more crons daily and more efficiently, it is better to have less historical data so the table size remains small.
N/A
=> Decrease time django-cron logs are kept to 90 days

extlinks/aggregates/cron.py, extlinks/common/cron.py, extlinks/links/cron.py
Changed the execution times of the monthly aggregates, backup, and total links crons.
The monthly aggregates were running at midnight, and they collided with the execution of the daily aggregates. By moving the time, we will ensure the tables will not be locked and will not overwhelm the database.
N/A
=> Change the execution times of some cron commands

.gitignore, README.md, requirements/django.txt
This patch adds [coverage](https://pypi.org/project/coverage/) to the project and updates the README with instructions on how to generate coverage reports. Coverage data can be generated by running `coverage run manage.py test`, and an HTML report can be generated with `coverage html` which gets written to `htmlcov/index.html`.
The test suite is lacking in many areas such as views and having coverage reporting setup in the project would help us increase our test coverage.
[T392250](https://phabricator.wikimedia.org/T392250)
N/A
[//]: # …
=> Add 'coverage' and updated README with instructions

extlinks/aggregates/management/helpers/aggregate_archive_command.py
Bug: T396681
Change-Id: I575614f739357850752be5d45441f58a1e8db5fe
Matching the try/except block structure with how we're doing it in linkevents_archive.py. 
We're seeing strange auth exceptions despite using the exact same `get_containers` method call. 
https://phabricator.wikimedia.org/T396681
Run tests locally, run commands locally. 
=> Match try/except block structure that we're using for linkevents_archive

extlinks/organisations/templates/organisations/organisation_detail.html, extlinks/organisations/views.py, extlinks/programs/templates/programs/program_detail.html, extlinks/programs/views.py, static/css/local.css
Bug: T399763
Change-Id: I57dbcbfd3f989728bbb2cfc9fd9b802fce394fcf
While working on [T370980: Export aggregates to static files](https://phabricator.wikimedia.org/T370980), [T396681: Create cron tasks for archiving aggregates](https://phabricator.wikimedia.org/T396681), we have modified where Wikilink obtains its data from. Since some of this work is still in flight, the data shown in Wikilink is erroneous. We should create several banners in organisations/ and programs/ to let the users know that the data shown at this time is inaccurate.
The banners should be removed once we merge the remaining PRs and verify that the data is correct again.
Informs users of ongoing maintenance. 
https://phabricator.wikimedia.org/T399763
Tested locally
What types of changes does your code introduce? Add …
=> Create banners to indicate wrong data on Wikilink

extlinks/aggregates/storage.py
Bug: T401431
Change-Id: Ic756e48b2080613489529c581f2b106591bdf70f
Describe your changes in detail following the [commit message guidelines]
- Added a guard clause type check before attempting to decompress our archive
- Added a guard clause type check before attempting to json load our decompressed archive
JSONDecodeError being thrown when decompression fails. 
https://phabricator.wikimedia.org/T401431
Manually tested, and ran unit tests. 
=> Add JSONDecodeError handling and return empty list

extlinks/common/templates/common/statistics_table.html
- Fixed label formatting
Bug: T401431
Change-Id: I35ecc95d91bb01d1c670d828c8006296634d4957
The "as of" date should be part of the "total" label rather than being part of the value.
More user-friendly UI. 
https://phabricator.wikimedia.org/T401431
Smoke tested this locally.
changed: 
to: 
=> Wikilink current total for JSTOR is showing incorrect amount

extlinks/aggregates/management/commands/fill_monthly_link_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_pageproject_aggregates.py, extlinks/aggregates/management/commands/fill_monthly_user_aggregates.py, extlinks/aggregates/management/commands/fill_top_organisations_totals.py, extlinks/aggregates/management/commands/fill_top_projects_totals.py, extlinks/aggregates/management/commands/fill_top_users_totals.py, extlinks/aggregates/management/helpers/aggregate_archive_command.py, extlinks/common/management/commands/__init__.py, extlinks/links/management/commands/linkevents_archive.py, extlinks/links/management/commands/linksearchtotal_collect.py, extlinks/settings/logging.py
- Add some proper logging to linksearchtotal_collect
- and exit(1) if db connection fails
- Use the same formatter for all handlers
- Stop using bespoke methods for logging to STDOUT/STDERR
- Use project BaseCommand class for all management commands
- `extlinks.common.management.commands.BaseCommand` provides locking
We've added management commands with inconsistent logging & locking approaches, making troubleshooting difficult.
https://phabricator.wikimedia.org/T403209
- Locally tested by running management commands manually and via crontab
cron logs:
```
crons-1  | 2025-09-02T20:06:09.463887909Z [INFO] reading wiki-list
crons-1  | 2025-09-02T20:06:09.464161829Z [INFO] connecting to db en
crons-1  | …
```
=> management command logging & locking cleanup

extlinks/organisations/templates/organisations/organisation_charts_include.html
[//]: # (Thank you for uploading a PR to Wikilinks (externallinks)!)
Fix link for Special:diff
Currently it produces a link like `https://en.wikipedia.org/wiki/Special:Diff1309325641`, which is missing a `/`.
=> Fix link for Special:diff

extlinks/aggregates/tests.py, extlinks/common/management/commands/__init__.py, extlinks/links/management/commands/linksearchtotal_collect.py, extlinks/links/tests.py, extlinks/settings/logging.py, requirements/django.txt
- Add retry logic to base command
- use tenacity library
- log at INFO level
- Remove some exception handling in linksearchtotal_collect command to enable retry
We were having quiet cron failure with no retries for linksearchtotal_collect which should run weekly. this change allows for some retries and makes the logs noisier for easier diagnostics.
https://phabricator.wikimedia.org/T403209
Tested by running locally
```
[INFO] Executing linksearchtotal_collect.py
[INFO] reading wiki-list
[INFO] connecting to db en
[WARNING] linksearchtotal_collect.py attempt 1 failed
[INFO] reading wiki-list
[INFO] connecting to db en
[WARNING] linksearchtotal_collect.py attempt 2 failed
[INFO] reading wiki-list
[INFO] connecting to db en
[WARNING] linksearchtotal_collect.py attempt 3 failed
[INFO] reading …
```
=> Add retry logic for all management commands
